AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Hyperlocal Tiles MVP backend. Cognito, DynamoDB, S3, Lambda + HTTP API.

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 512

Resources:
  # ========== DynamoDB Tables ==========
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Posts"
      AttributeDefinitions:
        - AttributeName: tileId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: tileId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  CommentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Comments"
      AttributeDefinitions:
        - AttributeName: postId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: postId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Users"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # ========== S3 Bucket for media ==========
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-media-${AWS::AccountId}"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ["*"]
            AllowedMethods: [GET, PUT, POST]
            AllowedHeaders: ["*"]

  # ========== Cognito ==========
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-users"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-client"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  # ========== HTTP API ==========
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - OPTIONS
        AllowHeaders:
          - "*"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient
            IdentitySource: "$request.header.Authorization"

  # ========== Lambda Functions ==========
  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/presign.handler
      CodeUri: .
      Environment:
        Variables:
          MEDIA_BUCKET: !Ref MediaBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MediaBucket
      Events:
        PresignApi:
          Type: HttpApi
          Properties:
            Path: /presign
            Method: post
            ApiId: !Ref Api

  CreatePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createPost.handler
      CodeUri: .
      Environment:
        Variables:
          POSTS_TABLE: !Ref PostsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTable
      Events:
        CreatePostApi:
          Type: HttpApi
          Properties:
            Path: /posts
            Method: post
            ApiId: !Ref Api

  FetchPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/fetchPosts.handler
      CodeUri: .
      Environment:
        Variables:
          POSTS_TABLE: !Ref PostsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PostsTable
      Events:
        FetchPostsApi:
          Type: HttpApi
          Properties:
            Path: /posts
            Method: get
            ApiId: !Ref Api
            Auth:
              Authorizer: NONE

  AddCommentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/addComment.handler
      CodeUri: .
      Environment:
        Variables:
          COMMENTS_TABLE: !Ref CommentsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentsTable
      Events:
        AddCommentApi:
          Type: HttpApi
          Properties:
            Path: /posts/{postId}/comments
            Method: post
            ApiId: !Ref Api

  FetchCommentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/fetchComments.handler
      CodeUri: .
      Environment:
        Variables:
          COMMENTS_TABLE: !Ref CommentsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CommentsTable
      Events:
        FetchCommentsApi:
          Type: HttpApi
          Properties:
            Path: /posts/{postId}/comments
            Method: get
            ApiId: !Ref Api
            Auth:
              Authorizer: NONE

  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getProfile.handler
      CodeUri: .
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        GetProfileApi:
          Type: HttpApi
          Properties:
            Path: /profile/{userId}
            Method: get
            ApiId: !Ref Api

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  MediaBucketName:
    Value: !Ref MediaBucket
